inmobiliaria/core/urls.py
from django.conf.urls import url
from django.urls import path
#Import personales
from . import views

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),

    path('nosotros/', views.nosotros, name='nosotros'),
    path('contacto/', views.contacto, name='contacto'),

    path('propiedades/', views.propiedades, name='propiedades'),
    path('propiedades/<int:prop_id>/', views.propiedad, name='propiedad'),
    
    path('buscador/', views.buscador, name='buscador'),

    path('tasaciones/', views.tasaciones, name='tasaciones'),
    path('proyectos/', views.proyectos, name='proyectos'),
    #Busquedas simplificadas
    path('ventas/', views.ventas, name='ventas'),
    path('alquileres/', views.alquileres, name='alquileres'),
]

inmobiliaria/inmobiliaria/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
#Import Extras

#import personales
from core import views as coreviews

urlpatterns = [
    #Standards
    path('admin/', admin.site.urls),
    url(r'^login/$',auth_views.LoginView.as_view(template_name="extras/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
    #Debug:
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inmobiliaria/core/models.py
#Import Genericos
from __future__ import unicode_literals
import datetime
from django.db import models

#Modulos extras:
from tinymce.models import HTMLField

#Choice Options
TIPO_NEGOCIO = (
    (1, 'Venta'),
    (2, 'Alquiler'),
    
    (9, 'Otro'),
)

TIPO_CONDICION = (
    (1, 'Excelente'),
    (2, 'Muy Buena'),
    (3, 'Buena'),
    (4, 'Mala'),

    (9, 'Otra'),
)

# Create your models here.
class TipoPropiedad(models.Model):
    nombre = models.CharField('Nombre', max_length=100)
    def __str__(self):
        return self.nombre

class Moneda(models.Model):
    nombre = models.CharField('Nombre', max_length=100)
    simbolo = models.CharField('Simbolo', max_length=5)
    def __str__(self):
        return self.nombre

class Etiqueta(models.Model):
    nombre = models.CharField('Nombre', max_length=100)
    def __str__(self):
        return self.nombre

class Zona(models.Model):
    nombre = models.CharField('Nombre', max_length=100)
    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre = models.CharField('Nombre', max_length=100)
    def __str__(self):
        return self.nombre

class Propiedad(models.Model):
    tipo_negocio = models.IntegerField(choices=TIPO_NEGOCIO, default=1)
    tipo_propiedad = models.ForeignKey(TipoPropiedad, on_delete=models.CASCADE, related_name="propiedades")
    nombre = models.CharField('Nombre', max_length=200)
    fecha = models.DateTimeField('Fecha de Publicacion', default=datetime.datetime.now)
    tmoneda = models.ForeignKey(Moneda, on_delete=models.CASCADE, null=True, blank=True, related_name="propiedades")
    precio = models.IntegerField('Precio', default=0)
    descripcion = HTMLField(null=True, blank=True)
    zonas = models.ManyToManyField(Zona, related_name="propiedades")
    direccion = models.CharField('Direccion', max_length=200)
    gps = models.URLField('Gmap Link', blank=True, null=True)
    dimensiones = models.CharField('Dimensiones', max_length=200)
    etiquetas = models.ManyToManyField(Etiqueta, blank=True, related_name="propiedades")
    servicios = models.ManyToManyField(Servicio, blank=True, related_name="propiedades")
    activa = models.BooleanField('Activa', default=True)
    class Meta:
        verbose_name_plural = 'Propiedades'
    def __str__(self):
        return self.nombre

class Foto(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name="fotos")
    orden = models.IntegerField(default=0)
    epigrafe = models.CharField('Nombre', max_length=25)
    imagen = models.FileField('Imagen', upload_to='propiedades/', null=True, blank=True)
    def __str__(self):
        return self.propiedad.nombre + str(self.orden)

class Sede(models.Model):
    nombre = models.CharField('Nombre', max_length=200)
    direccion = models.CharField('Direccion', max_length=200)
    localidad = models.CharField('Localidad', max_length=200)
    horario = models.CharField('Horario de Atencion', max_length=200)
    def __str__(self):
        return self.nombre

class Contacto(models.Model):
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE, related_name="contactos")
    nombre = models.CharField('Nombre', max_length=200)
    telefono = models.CharField('Telefono', max_length=100)
    def __str__(self):
        return self.sede.nombre + ': ' + self.nombre

class Proyecto(models.Model):
    autor = models.CharField('Nombre y Apellido', max_length=100)
    email = models.EmailField('Correo Electronico Personal')
    telefono = models.CharField('Telefono', max_length=50, blank=True, null=True)
    info_adicional = HTMLField()
    fecha_consulta = models.DateTimeField(auto_now_add=True)
    valida = models.BooleanField('Email Validado', default=False)
    respondida = models.BooleanField('Ya fue Respondida', default=False)
    def __str__(self):
        return u"%s por %s" % (self.email, self.info_adicional[:50])

class Tasacion(models.Model):
    autor = models.CharField('Nombre y Apellido', max_length=100)
    email = models.EmailField('Correo Electronico Personal')
    telefono = models.CharField('Telefono', max_length=50, blank=True, null=True)
    barrio = models.CharField('Barrio', max_length=100)
    calle = models.CharField('Calle', max_length=100)
    numeracion = models.CharField('Numeracion', max_length=100)
    tipo_propiedad = models.ForeignKey(TipoPropiedad, on_delete=models.CASCADE, related_name="tasaciones")
    metros_cubiertos = models.IntegerField('Mts2 Cubiertos', default=0)
    metros_semicubiertos = models.IntegerField('Mts2 SemiCubiertos', default=0)
    metros_descubiertos = models.IntegerField('Mts2 Descubiertos', default=0)
    antiguedad = models.IntegerField('Antiguedad', default=0)
    tipo_tasacion = models.IntegerField(choices=TIPO_NEGOCIO, default=1)
    condiciones = models.IntegerField(choices=TIPO_CONDICION, default=1)
    info_adicional = HTMLField()
    fecha_consulta = models.DateTimeField(auto_now_add=True)
    valida = models.BooleanField('Email Validado', default=False)
    respondida = models.BooleanField('Ya fue Respondida', default=False)
    def __str__(self):
        return u"%s por %s de %s en %s" % (self.email, self.get_tipo_tasacion_display(), self.tipo_propiedad.nombre, self.barrio)

inmobiliaria/core/forms.py
#Import Standard
from django import forms
from django.forms import ModelForm
from django.db import models

#Import del Proyecto
from .models import Tasacion, Proyecto

#Definimos nuestros Formularios

class TasacionForm(ModelForm):
    class Meta:
        model = Tasacion
        fields = '__all__'
        widgets = {
                    'valida': forms.HiddenInput(),
                    'respondida': forms.HiddenInput()}

class ProyectoForm(ModelForm):
    class Meta:
        model = Proyecto
        fields = '__all__'
        widgets = {
                    'valida': forms.HiddenInput(),
                    'respondida': forms.HiddenInput()}

inmobiliaria/core/views.py
#Modulos Standards
from django.shortcuts import render
from django.db.models import Q

#Import Propios
from .models import TIPO_NEGOCIO, TipoPropiedad, Etiqueta, Zona
from .models import Propiedad, Foto
from .models import Sede
from .functions import obtener_propiedades
from .forms import TasacionForm, ProyectoForm

# Create your views here.
def home(request):
    props = obtener_propiedades(4)
    return render(request, 'home.html', {'propiedades': props, })

def nosotros(request):
    return render(request, 'nosotros.html', { })

def contacto(request):
    sedes = Sede.objects.all()
    return render(request, 'contacto.html', {'sedes': sedes, })

def propiedades(request, props=None):
    tipos_propiedad = TipoPropiedad.objects.all()
    zonas = Zona.objects.all()
    etiquetas = Etiqueta.objects.all()
    if not props:
        props = []
        if request.method == 'POST':
            if request.POST.get('search_box'): #En caso de que se haya realizado una busqueda
                texto = request.POST.get('search_box')
                props = Propiedad.objects.filter(
                    Q(nombre__icontains=texto)|
                    Q(descripcion__icontains=texto)).distinct()
            elif 'filtrar' in request.POST:#Si se uso el sistema de filtros
                props = obtener_propiedades()#buscamos todas las propiedades
                #Filtramos por tipo de negocio
                filtro = []
                for tn in TIPO_NEGOCIO:
                    if "tn-"+str(tn[0]) in request.POST:
                        filtro.append(tn[0])
                if filtro:
                    props = props.filter(tipo_negocio__in=filtro)
                #Filtramos por tipo de propiedad
                filtro = []
                for tp in tipos_propiedad:
                    if "tp-"+str(tp.id) in request.POST:
                        filtro.append(tp)
                if filtro:
                    props = props.filter(tipo_propiedad__in=filtro)
                #Filtramos por zonas
                filtro = []
                for zona in zonas:
                    if "zona-"+str(zona.id) in request.POST:
                        filtro.append(zona)
                if filtro:
                    props = props.filter(zonas__in=filtro)
                #Filtramos por etiquetas
                filtro = []
                for etiqueta in etiquetas:
                    if "etiqueta-"+str(etiqueta.id) in request.POST:
                        filtro.append(etiqueta)
                if filtro:
                    props = props.filter(etiquetas__in=filtro)
            props = props.filter(activa=True)
        else:
            props = obtener_propiedades(12)
    return render(request, 'propiedades.html', {'propiedades': props, 'tipos_negocio': TIPO_NEGOCIO, 'tipos_propiedad': tipos_propiedad, 'etiquetas': etiquetas, 'zonas': zonas,})

def propiedad(request, prop_id):
    prop = Propiedad.objects.get(pk=prop_id)
    return render(request, 'propiedad.html', {'prop': prop, })

def buscador(request):
    tipos_propiedad = TipoPropiedad.objects.all()
    zonas = Zona.objects.all()
    etiquetas = Etiqueta.objects.all()
    return render(request, 'filtrador.html', {'tipos_negocio': TIPO_NEGOCIO, 'tipos_propiedad': tipos_propiedad, 'etiquetas': etiquetas, 'zonas': zonas,})

def ventas(request):
    props = Propiedad.objects.filter(tipo_negocio=1, activa=True)
    return propiedades(request, props)

def alquileres(request):
    props = Propiedad.objects.filter(tipo_negocio=2, activa=True)
    return propiedades(request, props)

def tasaciones(request):
    enviado = False
    if request.method == 'POST':
        form = TasacionForm(request.POST)
        if form.is_valid():
            form.save()
            enviado = True
    else:
        form = TasacionForm()
    return render(request, 'tasaciones.html', {'form': form, 'enviado': enviado})

def proyectos(request):
    enviado = False
    if request.method == 'POST':
        form = ProyectoForm(request.POST)
        if form.is_valid():
            form.save()
            enviado = True
    else:
        form = ProyectoForm()
    return render(request, 'proyectos.html', {'form': form, 'enviado': enviado})

inmobiliaria/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include "base/head.html" %}
  <body id="body">
    {% include "base/menu.html" %}
    {% include "base/header.html" %}
    {% include "base/buscador.html" %}
    <main>
      {% block content %}
        <!-- Aqui ingresa el codigo operativo de la view llamada -->
      {% endblock %}
    </main>
    {% include "base/footer.html" %}
    {% include "base/scripts.html" %}
  </body>
</html>

inmobiliaria/core/templates/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9 contactos">
                {% for sede in sedes %}
                    <div class="col-md-5">
                        <h1>{{sede.localidad}}</h1>
                        <div class="col-md-12 sedes">
                            <div class="col-md-6 telefonos divisor">
                                <img class="icono" src="{% static 'img/icons/telefono.png' %}"/>
                                {% for contacto in sede.contactos.all %}
                                    <p class="nombre">{{contacto.nombre}}</p>
                                    <p class="telefono">{{contacto.telefono}}</p>
                                {% endfor %}
                            </div>
                            <div class="col-md-6" style="text-align: left">
                                <img class="icono" src="{% static 'img/icons/ubicacion.png' %}"/>
                                <div class="sede">
                                    <h1>{{sede.direccion}}</h1>
                                </div>
                            </div>
                            <div class="col-md-12 horario">
                                <p class="titulo">HORARIO DE ATENCION:</p>
                                <p class="horas">{{sede.horario}}</p>
                            </div>
                            <img class="mascara_abajo" src="{% static 'img/gpsMascara.png' %}"/>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-3 quebuscas">
                <h1>QUE ESTAS BUSCANDO?</h1>
                    <div class="col-md-6 contacto">
                        <a href='/ventas/'>
                            <img src="{% static 'img/icons/ventas.png' %}"/>
                            <p>Ventas</p>
                        </a>
                    </div>
                    <div class="col-md-6 contacto">
                        <a href='/alquileres/'>
                            <img class="imagen" src="{% static 'img/icons/alquileres.png' %}"/>
                            <p>Alquileres</p>
                        </a>
                    </div>
                    <div class="col-md-6 contacto">
                        <a href='/proyectos/'>
                            <img class="imagen" src="{% static 'img/icons/proyectos.png' %}"/>
                            <p>Proyectos</p>
                        </a>
                    </div>
                    <div class="col-md-6 contacto">
                        <a href='/tasaciones/'>
                            <img class="imagen" src="{% static 'img/icons/tasaciones.png' %}"/>
                            <p>Tasaciones</p>
                        </a>
                    </div>
                <h1>CONTACTANOS Y CRECÉ CON NOSOTROS</h1>
            </div>
        </div>
    </div>
{% endblock %}

inmobiliaria/core/templates/filtrador.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 propiedad">
                <div class="full_filtros">
                    {% include "utils/filtros.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inmobiliaria/core/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="destacados container-fluid">
        <div class="row">
            {% for prop in propiedades %}
                <div class="col-md-3">
                    <a href="/propiedades/{{prop.id}}">
                        <div class="destacado">
                            <div class="imagen">
                                <p class="tipo_destacado">{{prop.get_tipo_negocio_display}} {{prop.tipo_propiedad.nombre}}</p>
                                <img class="marmol" src="{% static 'img/marmol.png' %}">
                                <img class="foto" src="/archivos/{{prop.fotos.all.0.imagen}}">
                            </div>
                            <div class="texto">
                                <h1 class="titulo">{{prop.nombre|upper}}</h1>
                                <p><img class="icono" src="{% static 'img/icons/ubicacion.png' %}"/>{{prop.direccion}}</p>
                                <p class="tags center-block">
                                    {{prop.dimensiones}}
                                    :
                                    {% for tag in prop.etiquetas.all %}
                                        {{tag.nombre}}
                                    {% endfor %}
                                </p>
                                <img class="info center-block" src="{% static 'img/info.png' %}"/>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="buscando">
        <h1>¿QUÉ ESTÁS BUSCANDO?</h1>
        <div class="buscando_items container">
            <div class="col-md-2">
            </div>
            <a href='/ventas/'>
                <div class="col-md-2 padd5">
                    <img class="imagen" src="{% static 'img/icons/ventas.png' %}"/>
                    <p>VENTAS</p>
                </div>
            </a>
            <a href='/alquileres/'>
                <div class="col-md-2 padd5">
                <img class="imagen" src="{% static 'img/icons/alquileres.png' %}"/>
                <p>ALQUILERES</p>
                </div>
            </a>
            <a href='/proyectos/'>
                <div class="col-md-2 padd5">
                <img class="imagen" src="{% static 'img/icons/proyectos.png' %}"/>
                <p>PROYECTOS</p>
                </div>
            </a>
            <a href='/tasaciones/'>
                <div class="col-md-2 padd5">
                <img class="imagen" src="{% static 'img/icons/tasaciones.png' %}"/>
                <p>TASACIONES</p>
                </div>
            </a>
            <div class="col-md-2">
            </div>
        </div>
    </div>

    <div class="cierre">
        <div class="mensaje">
            <p>Conocemos la importancia de los movimientos inmobiliarios.
            Por eso, nuestra prioridad es brindar a nuestros clientes una variada gama de servicios para que puedan gestionar todos sus proyectos junto a nosotros,
            dentro del marco de confianza y seguridad que nuestro establecimiento les ofrece.
            Contamos con propiedades de altísima calidad y excelentes ubicaciones, además de asesoramiento en proyectos y administración de propiedades.</p>
        </div>
        <div class="invitacion">
            <h1>CONTACTANOS Y CRECÉ CON NOSOTROS</h1>
        </div>
    </div>

{% endblock %}

inmobiliaria/core/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9 nosotros">
                <h1>¿QUIÉNES SOMOS?</h1>
                <p>Rodriguez Quiroga, es una empresa de servicios dedicada a asesorar, acompañar y generar negocios inmobiliarios, 
                trabajando constantemente para brindar la mejor atención a nuestros clientes con seriedad, respeto y profesionalismo.
                Con una extensa experiencia en Jujuy, contamos con dos oficinas estratégicamente ubicadas en la capital jujeña y en Humahuaca, 
                logrando satisfacer distintas demandas y generando nuevas oportunidades de negocio.</p>

                <h1>NUESTRA CULTURA Y MISIÓN:</h1>
                <p>Lograr una mejora continua en el nivel de satisfacción de los clientes, perfeccionando y adaptando constantemente nuestra gama de servicios. 
                Construir una estrecha relación con los clientes, guiarlos en el proceso de compra y venta, atenderlos con dedicación, calidez y transparencia.
                Fomentar el desarrollo, lealtad y espíritu de equipo de quienes trabajan en la empresa como el 
                medio privilegiado para alcanzar el logro de nuestra visión.</p>

                <h1>VISIÓN:</h1>
                <p>Generar valor en los negocios inmobiliarios, estar a la vanguardia del mercado, brindando un servicio profesional y especializado.</p>
            </div>
            {% include "utils/quebuscas.html" %}
        </div>
    </div>
{% endblock %}

inmobiliaria/core/templates/propiedad.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 propiedad col-md-offset-2">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <h1 class="prop_nombre">{{prop.tipo_propiedad}} {{prop.nombre}}</h1>
                            <p class="prop_descripcion">{{prop.descripcion | safe | slice:": 500"}}...</p>
                            <p><b></b></p>
                            {% if prop.zonas %}
                                <p>
                                    <b>Zona:</b>
                                    {% for z in prop.zonas.all %}
                                        {{z.nombre}}, 
                                    {% endfor %}
                                </p>
                            {% endif %}
                            
                            <p>
                                <b>Direccion:</b>{{prop.direccion}}
                                {% if prop.gps %}
                                    <a href="{{prop.gps}}" target="_blank"><img class="icono" src="{% static 'img/icons/gmap.png' %}"/></a>
                                {% endif %}
                            </p>

                            <p><b>Superficie:</b>{{prop.dimensiones}}</p>
                            
                            {% if prop.etiquetas.all %}
                                <p>
                                    <b>Etiquetas:</b>
                                    {% for etiqueta in prop.etiquetas.all %}
                                        {{etiqueta.nombre}}, 
                                    {% endfor %}
                                </p>
                            {% endif %}
                            
                            {% if prop.servicios.all %}
                                <p>
                                    <b>Servicios:</b>
                                    {% for servicio in prop.servicios.all %}
                                        {{servicio.nombre}}, 
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                        <div class="col-md-6 nopadding">
                            {% with fotos=prop.fotos.all %}     
                                {% include "utils/carousel.html" %}
                            {% endwith %}
                            <p class="prop_tipo_negocio">{{prop.get_tipo_negocio_display}}</p>
                            <p class="prop_precio">{{prop.tmoneda.simbolo}} {{prop.precio}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inmobiliaria/core/templates/propiedades.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="destacados container-fluid">
                    <div class="row">
                        {% if propiedades %}
                            {% for prop in propiedades %}
                                <div class="col-md-4">
                                    <a href="/propiedades/{{prop.id}}">
                                        <div class="destacado">
                                            <div class="imagen">
                                                <p class="tipo_destacado">{{prop.get_tipo_negocio_display}} {{prop.tipo_propiedad.nombre}}</p>
                                                <img class="marmol" src="{% static 'img/marmol.png' %}">
                                                <img class="foto" src="/archivos/{{prop.fotos.all.0.imagen}}">
                                            </div>
                                            <div class="texto">
                                                <h1>{{prop.nombre}}</h1>
                                                <p>
                                                    <img class="icono" src="{% static 'img/icons/ubicacion.png' %}"/>
                                                    {{prop.direccion}}
                                                </p>
                                                <p class="tags center-block">
                                                    {{prop.dimensiones}}
                                                    :
                                                    {% for tag in prop.etiquetas.all %}
                                                    {{tag.nombre}}
                                                    {% endfor %}
                                                </p>
                                                <img class="info center-block" src="{% static 'img/info.png' %}"/>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-md-9" style="float:none;margin:auto;margin-top:15%;">
                                <h1>No se han encontrado propiedades disponibles con los datos de búsqueda informados</h1>
                            </div>
                        {% endif %} 
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                {% include "utils/filtros.html" %}
            </div>
        </div>
{% endblock %}

inmobiliaria/core/templates/proyectos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 tasacion_left">
                <h1 style="font-size:2em;">ANIMATE A TU</h1>
                <h1>PROYECTO!</h1>
                <p>Si tenés un sueño, un proyecto del que estás entusiasmado y lo querés compartir con nosotros
                para que lo analicemos y le demos forma, no dudes en contactarnos y comentarnos tus ideas. 
                Las ideas son lo más valioso que tenemos, pero a veces necesitamos que otro nos de un empujón para saltar 
                a realizar nuestro proyecto.  Animate a completar el formulario y nos pondremos en contacto con vos lo antes posible!</p>
            </div>
            {% if not enviado %}
                <div class="col-md-6">
                    <form action=""  name="proyecto" method="POST">
                        {% csrf_token %}
                        <div class="proyecto_form" id="form1">
                                <h1 class="titulo">Datos del Propietario</h1>
                                <label>Nombre y apellido:</label>{{form.autor}}<br>
                                <label>Direccion Email:</label>{{form.email}}<br>
                                <label>Telefono de Contacto:</label>{{form.telefono}}<br>
                                <label>Contanos brevemente tu idea:</label><br>
                                {{form.info_adicional}}<br>
                                <input class="boton" type="submit" value="Enviar">
                        </div>
                    </form>
                </div>
            {% else %}
                <div class="col-md-6">
                    <div class="tasacion_enviado">
                        <p class="cabecera">Sus datos se enviaron correctamente</p>
                        <h1 class="titulo">¡ GRACIAS !</h1>
                        <p>Nuestro equipo se comunicara con usted a la brevedad.
                            Cualquier consulta que tenga, dirijase a nuestra seccion de contactos. Ahi le brindaremos 
                            toda la informacion necesaria para llamarnos, enviarnos un E-mail con sus dudas o visitar 
                            nuestras oficinas.</p>
                    </div>
                </div>
            {% endif %}       
            {% include "utils/quebuscas.html" %}
        </div>
    </div>
{% endblock %}